//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Democrazy.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Coalition
    {
        public Coalition()
        {
            this.PoliticalParties = new HashSet<PoliticalParty>();
        }
    
        public int Id { get; set; }
        public bool isInOpposition { get; set; }
        public string Name { get; set; }
    
        public virtual ICollection<PoliticalParty> PoliticalParties { get; set; }
    }
}
