//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Democrazy.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Country
    {
        public Country()
        {
            this.Laws = new HashSet<Law>();
            this.PoliticalParties = new HashSet<PoliticalParty>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string NumberOfInhabitants { get; set; }
        public Government_Type GovernmentType { get; set; }
    
        public virtual Parliament Parliament { get; set; }
        public virtual ICollection<Law> Laws { get; set; }
        public virtual ICollection<PoliticalParty> PoliticalParties { get; set; }
    }
}
