//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Democrazy.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CrazyContext : DbContext
    {
        public CrazyContext()
            : base("name=CrazyContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<User> Users { get; set; }
        public DbSet<Law> Laws { get; set; }
        public DbSet<LawProposal> LawProposals { get; set; }
        public DbSet<SeatType> SeatsTypes { get; set; }
        public DbSet<Seat> Seats { get; set; }
        public DbSet<Parliament> Parliaments { get; set; }
        public DbSet<Lower_House> Lower_Houses { get; set; }
        public DbSet<PoliticalParty> PoliticalParties { get; set; }
        public DbSet<Country> Countries { get; set; }
        public DbSet<Coalition> Coalitions { get; set; }
        public DbSet<Paragraph> Paragraphs { get; set; }
        public DbSet<Sex> Sexes { get; set; }
        public DbSet<Paragraph_Translation> Paragraph_TranslationSet { get; set; }
        public DbSet<Law_Translation> Law_Translations { get; set; }
        public DbSet<Paragraph_Change> Paragraph_Changes { get; set; }
        public DbSet<Law_Translation_Vote> Law_Translation_Votes { get; set; }
        public DbSet<Paragraph_Translate_Vote> Paragraph_Translate_Votes { get; set; }
        public DbSet<Paragraph_Change_Vote> Paragraph_Change_Votes { get; set; }
    }
}
