//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Democrazy.Data
{
    using System;
    
    public enum Government_Type : int
    {
        Republic = 1,
        Constitutional_Monarchy = 2,
        Dictatorship = 3
    }
}
