//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Democrazy.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Law
    {
        public Law()
        {
            this.Voters = new HashSet<Seat>();
            this.Paragraphs = new HashSet<Paragraph>();
            this.Law_Translations = new HashSet<Law_Translation>();
        }
    
        public int Id { get; set; }
        public int MemberId { get; set; }
        public int CountryId { get; set; }
        public string Name { get; set; }
        public string Summary { get; set; }
        public string AliasName { get; set; }
    
        public virtual ICollection<Seat> Voters { get; set; }
        public virtual ICollection<Paragraph> Paragraphs { get; set; }
        public virtual ICollection<Law_Translation> Law_Translations { get; set; }
    }
}
