//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Democrazy.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Law_Translation_Vote
    {
        public int Id { get; set; }
        public short Vote_Value { get; set; }
        public int Law_TranslationId { get; set; }
        public int UserId { get; set; }
    }
}
