//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Democrazy.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Paragraph_Change
    {
        public Paragraph_Change()
        {
            this.Votes = new HashSet<Paragraph_Change_Vote>();
        }
    
        public int Id { get; set; }
        public string Reason { get; set; }
        public int ParagraphId { get; set; }
        public string Text { get; set; }
        public System.DateTime StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public RevisionType RevisionType { get; set; }
    
        public virtual ICollection<Paragraph_Change_Vote> Votes { get; set; }
    }
}
