//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Democrazy.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public User()
        {
            this.Paragraph_Translations = new HashSet<Paragraph_Translation>();
            this.Law_Translations = new HashSet<Law_Translation>();
            this.Paragraph_Translate_Votes = new HashSet<Paragraph_Translate_Vote>();
            this.Law_Translation_Votes = new HashSet<Law_Translation_Vote>();
            this.Paragraph_Change_Votes = new HashSet<Paragraph_Change_Vote>();
        }
    
        public int Id { get; set; }
        public string Password { get; set; }
        public string UserName { get; set; }
        public UserLevel UserLevel { get; set; }
        public int CountryId { get; set; }
        public int SexId { get; set; }
    
        public virtual ICollection<Paragraph_Translation> Paragraph_Translations { get; set; }
        public virtual ICollection<Law_Translation> Law_Translations { get; set; }
        public virtual ICollection<Paragraph_Translate_Vote> Paragraph_Translate_Votes { get; set; }
        public virtual ICollection<Law_Translation_Vote> Law_Translation_Votes { get; set; }
        public virtual ICollection<Paragraph_Change_Vote> Paragraph_Change_Votes { get; set; }
    }
}
